# Generated by Django 4.2.6 on 2023-10-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Тип Слайдера')),
                ('title', models.CharField(max_length=60, verbose_name='Название Слайдера')),
            ],
        ),
    ]
