# Generated by Django 4.2.6 on 2023-10-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingswebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
    ]
