# Generated by Django 4.2.6 on 2023-10-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingswebsite', '0002_alter_slider_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('facebook_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Фейсбук')),
                ('instagram_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Инстраграм')),
                ('twitter_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Твиттер')),
                ('pinterest_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Пинтерест')),
                ('developer', models.CharField(max_length=50, verbose_name='Разработчик')),
                ('sliders', models.ManyToManyField(blank=True, to='settingswebsite.slider', verbose_name='Слайдеры')),
            ],
            options={
                'verbose_name': 'Настройка Сайта',
                'verbose_name_plural': 'Настройки Сайта',
            },
        ),
    ]
