# Generated by Django 4.2.6 on 2023-10-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingswebsite', '0003_settingswebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=1, upload_to='sliders/', verbose_name='Изображение Слайдера'),
            preserve_default=False,
        ),
    ]
